[package]
name = "torrentio-neo"
version = "0.1.2"
description = "Torrentio Neo desktop app"
authors = ["Torrentio Neo"]
edition = "2021"
build = "build.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
